#!/usr/bin/env python3
"""Generate loaderless Vulkan entry points for switchVK's ICD-only SDK."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

CALL_RE = re.compile(r"\b(vk[A-Z][A-Za-z0-9_]*)\s*\(")
PROTO_RE = re.compile(
    r"VKAPI_ATTR\s+(?P<result>.+?)\s+VKAPI_CALL\s+"
    r"(?P<name>vk[A-Z][A-Za-z0-9_]*)\s*\((?P<params>.*?)\)\s*;",
    re.S,
)
SPECIAL = {
    "vkCreateInstance", "vkDestroyInstance", "vkGetInstanceProcAddr",
    "vkCreateDevice", "vkDestroyDevice", "vkGetDeviceProcAddr",
}


def argument_names(params: str) -> list[str]:
    params = params.strip()
    if not params or params == "void":
        return []
    names: list[str] = []
    depth = 0
    start = 0
    pieces: list[str] = []
    for index, char in enumerate(params + ","):
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
        elif char == "," and depth == 0:
            pieces.append(params[start:index].strip())
            start = index + 1
    for piece in pieces:
        match = re.search(r"([A-Za-z_][A-Za-z0-9_]*)\s*(?:\[[^\]]*\])?$",
                          piece)
        if not match:
            raise ValueError(f"cannot extract argument name from {piece!r}")
        names.append(match.group(1))
    return names


def fail_return(result: str) -> str:
    if result == "void":
        return "  return;"
    if result == "VkResult":
        return "  return VK_ERROR_INITIALIZATION_FAILED;"
    return f"  return ({result})0;"


def wrapper(result: str, name: str, params: str) -> str:
    args = ", ".join(argument_names(params))
    call = f"fn({args})"
    body = [
        f"VKAPI_ATTR {result} VKAPI_CALL {name}({params}) {{",
        f"  PFN_{name} fn = (PFN_{name})loader_resolve(\"{name}\");",
        f"  if (!fn) {{ {fail_return(result).strip()} }}",
    ]
    if result == "void":
        body.append(f"  {call};")
    else:
        body.append(f"  return {call};")
    body.append("}")
    return "\n".join(body)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--headers", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("sources", nargs="+", type=Path)
    args = parser.parse_args()

    used: set[str] = set()
    for root in args.sources:
        for source in root.rglob("*"):
            if source.suffix not in {".c", ".cc", ".cpp", ".h", ".hpp"}:
                continue
            try:
                used.update(CALL_RE.findall(source.read_text(encoding="utf-8")))
            except UnicodeDecodeError:
                used.update(CALL_RE.findall(source.read_text(encoding="latin-1")))

    prototypes: dict[str, tuple[str, str]] = {}
    for header in args.headers.rglob("*.h"):
        text = header.read_text(encoding="utf-8")
        for match in PROTO_RE.finditer(text):
            prototypes.setdefault(match.group("name"), (
                " ".join(match.group("result").split()),
                " ".join(match.group("params").split()),
            ))

    ignored = {"vk_icdGetInstanceProcAddr", "vkSetDeviceLoaderData"}
    missing = sorted(name for name in used if name not in prototypes and
                     name not in ignored)
    if missing:
        raise SystemExit("Missing Vulkan prototypes: " + ", ".join(missing))

    regular = sorted(name for name in used if name not in SPECIAL and
                     name not in ignored)
    generated = [
        "/* Generated by tools/generate_vulkan_loader.py. */",
        "#include <stdlib.h>",
        "#include <vulkan/vulkan.h>",
        "",
        "extern VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL",
        "vk_icdGetInstanceProcAddr(VkInstance instance, const char *name);",
        "",
        "static VkInstance g_loader_instance;",
        "static VkDevice g_loader_device;",
        "static PFN_vkGetDeviceProcAddr g_loader_get_device_proc;",
        "",
        "static PFN_vkVoidFunction loader_resolve(const char *name) {",
        "  PFN_vkVoidFunction function = NULL;",
        "  if (g_loader_device) {",
        "    if (!g_loader_get_device_proc)",
        "      g_loader_get_device_proc = (PFN_vkGetDeviceProcAddr)",
        "          vk_icdGetInstanceProcAddr(g_loader_instance, \"vkGetDeviceProcAddr\");",
        "    if (g_loader_get_device_proc)",
        "      function = g_loader_get_device_proc(g_loader_device, name);",
        "  }",
        "  if (!function)",
        "    function = vk_icdGetInstanceProcAddr(g_loader_instance, name);",
        "  return function;",
        "}",
        "",
        "VKAPI_ATTR VkResult VKAPI_CALL vkCreateInstance(",
        "    const VkInstanceCreateInfo *info, const VkAllocationCallbacks *allocator,",
        "    VkInstance *instance) {",
        "  PFN_vkCreateInstance function = (PFN_vkCreateInstance)",
        "      vk_icdGetInstanceProcAddr(VK_NULL_HANDLE, \"vkCreateInstance\");",
        "  if (!function) return VK_ERROR_INITIALIZATION_FAILED;",
        "  VkResult result = function(info, allocator, instance);",
        "  if (result == VK_SUCCESS && instance) g_loader_instance = *instance;",
        "  return result;",
        "}",
        "",
        "VKAPI_ATTR void VKAPI_CALL vkDestroyInstance(",
        "    VkInstance instance, const VkAllocationCallbacks *allocator) {",
        "  PFN_vkDestroyInstance function = (PFN_vkDestroyInstance)",
        "      vk_icdGetInstanceProcAddr(instance, \"vkDestroyInstance\");",
        "  if (function) function(instance, allocator);",
        "  if (instance == g_loader_instance) {",
        "    g_loader_instance = VK_NULL_HANDLE; g_loader_device = VK_NULL_HANDLE;",
        "    g_loader_get_device_proc = NULL;",
        "  }",
        "}",
        "",
        "VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL vkGetInstanceProcAddr(",
        "    VkInstance instance, const char *name) {",
        "  return vk_icdGetInstanceProcAddr(instance, name);",
        "}",
        "",
        "VKAPI_ATTR VkResult VKAPI_CALL vkCreateDevice(",
        "    VkPhysicalDevice physical, const VkDeviceCreateInfo *info,",
        "    const VkAllocationCallbacks *allocator, VkDevice *device) {",
        "  PFN_vkCreateDevice function = (PFN_vkCreateDevice)",
        "      vk_icdGetInstanceProcAddr(g_loader_instance, \"vkCreateDevice\");",
        "  if (!function) return VK_ERROR_INITIALIZATION_FAILED;",
        "  VkResult result = function(physical, info, allocator, device);",
        "  if (result == VK_SUCCESS && device) g_loader_device = *device;",
        "  return result;",
        "}",
        "",
        "VKAPI_ATTR void VKAPI_CALL vkDestroyDevice(",
        "    VkDevice device, const VkAllocationCallbacks *allocator) {",
        "  PFN_vkDestroyDevice function = (PFN_vkDestroyDevice)loader_resolve(\"vkDestroyDevice\");",
        "  if (function) function(device, allocator);",
        "  if (device == g_loader_device) g_loader_device = VK_NULL_HANDLE;",
        "}",
        "",
        "VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL vkGetDeviceProcAddr(",
        "    VkDevice device, const char *name) {",
        "  if (!g_loader_get_device_proc)",
        "    g_loader_get_device_proc = (PFN_vkGetDeviceProcAddr)",
        "        vk_icdGetInstanceProcAddr(g_loader_instance, \"vkGetDeviceProcAddr\");",
        "  return g_loader_get_device_proc ? g_loader_get_device_proc(device, name) : NULL;",
        "}",
        "",
    ]
    for name in regular:
        result, params = prototypes[name]
        generated.extend([wrapper(result, name, params), ""])

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(generated), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
